version: "3"
services:
  frontend:
    stdin_open: true
    tty: true
    container_name: client-all
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - '.:/app'
      - '/app/src'
      - '/app/node_modules'